disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ty's World"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "Monday, January 2, 2006"
logo = "img/kitten2.svg"
# secondaryLogo = "img/favicon.png"
description = "My small grove. An attempt to reclaim what is mine."
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Talha Yildirim"
# email = "talha.yildirim@uwaterloo.ca"
image = "/img/talha_pfp.png"
imageQuality = 96
headline = "I'm just a boy."
bio = "A little bit of this and a little bit of that type of person."
links = [
  { spotify = "https://open.spotify.com/user/efkep0xtgnbczk72wiyhtlcnt" },
  { youtube = "https://www.youtube.com/@_TheBlindLeadingTheBlind" },
  { linkedin = "https://www.linkedin.com/in/talha-yildirimm/" },
  { github = "https://github.com/pacman-ty" },
  #     { email = "mailto:hello@your_domain.com" },
  #     { link = "https://link-to-some-website.com/" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { apple = "https://www.apple.com" },
  #     { blogger = "https://username.blogspot.com/" },
  #     { bluesky = "https://bsky.app/profile/username" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  #     { discord = "https://discord.gg/invitecode" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { facebook = "https://facebook.com/username" },
  #     { flickr = "https://www.flickr.com/photos/username/" },
  #     { foursquare = "https://foursquare.com/username" },
  #     { gitlab = "https://gitlab.com/username" },
  #     { google = "https://www.google.com/" },
  #     { hashnode = "https://username.hashnode.dev" },
  #     { instagram = "https://instagram.com/username" },
  #     { itch-io = "https://username.itch.io" },
  #     { keybase = "https://keybase.io/username" },
  #     { kickstarter = "https://www.kickstarter.com/profile/username" },
  #     { lastfm = "https://lastfm.com/user/username" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { medium = "https://medium.com/username" },
  #     { microsoft = "https://www.microsoft.com/" },
  #     { orcid = "https://orcid.org/userid" },
  #     { patreon = "https://www.patreon.com/username" },
  #     { pinterest = "https://pinterest.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { snapchat = "https://snapchat.com/add/username" },
  #     { soundcloud = "https://soundcloud.com/username" },
  #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #     { steam = "https://steamcommunity.com/profiles/userid" },
  #     { telegram = "https://t.me/username" },
  #     { threads = "https://www.threads.net/@username" },
  #     { tiktok = "https://tiktok.com/@username" },
  #     { tumblr = "https://username.tumblr.com" },
  #     { twitch = "https://twitch.tv/username" },
  #     { twitter = "https://twitter.com/username" },
  #     { x-twitter = "https://twitter.com/username" },
  #     { whatsapp = "https://wa.me/phone-number" },
  #     { ko-fi = "https://ko-fi.com/username" },
  #     { codeberg = "https://codeberg.org/username"},
]
