# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

[[main]]
name = "About"
pageRef = "about"
weight = 1

[[main]]
name = "Blogs"
pageRef = "blogs"
weight = 2

[[main]]
name = "Books"
parent = "Blogs"
pageRef = "books"
weight = 20

[[main]]
name = "Movies"
parent = "Blogs"
pageRef = "movies"
weight = 30

[[main]]
name = "Tech"
parent = "Blogs"
pageRef = "tech"
weight = 40

[[main]]
name = "Essays"
pageRef = "essays"
weight = 3

[[main]]
name = "Music"
pageRef = "music"
weight = 4


[[main]]
name = "Photography"
pageRef = "photography"
weight = 5

[[main]]
name = "Portfolio"
url = "https://ty-world.vercel.app/"
weight = 6

[[subnavigation]]
name = "Broken Car"
pre = "paw1"
pageRef = "broken_car"
weight = 1

[[subnavigation]]
name = "The Blind Leading the Blind"
pre = "youtube"
pageRef = "blb"
weight = 2

[[subnavigation]]
name = "Github"
pre = "github"
weight = 3

# [[subnavigation]]
# name = "LinkedIn"
# pre = "linkedin"
# url = "https://www.linkedin.com/in/talha-yildirimm/"
# weight = 4

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Authors"
pageRef = "authors"
weight = 10

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 40

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 30

[[footer]]
name = "Series"
pageRef = "series"
weight = 20
