# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"   # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = false

replyByEmail = false

mainSections = ["blogs", "essays", "music"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/eva_background.png" # used as default for background images 
defaultFeaturedImage = "/img/eva_background.png"   # used as default for featured images in all articles

# highlightCurrentMenuArea = true
# smartTOC = true
# smartTOCHideUnfocusedChildren = true

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"

[header]
layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"                      # valid options: page, profile, hero, card, background, custom
homepageImage = "/img/eva_background2.png" # used in: hero, and card
showRecent = true
showRecentItems = 12
showMoreLink = true
showMoreLinkDest = "/categories/"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = false               # only used when layout equals background

[article]
showDate = true
showDateOnlyInArticle = true
showDateUpdated = false
showAuthor = false
# showAuthorBottom = false
showHero = true
heroStyle = "background"                                            # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true                                         # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true                                  # only used when heroStyle equals background
showBreadcrumbs = true
showDraftLabel = true
showEdit = true
editURL = "https://github.com/pacman-ty/ty-world/tree/main/content"
editAppendPath = true
seriesOpened = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
showSummary = true
# showComment = true
showZenMode = false
sharingLinks = [
  "linkedin",
  "twitter",
  "reddit",
  "pinterest",
  "facebook",
  "email",
  "whatsapp",
  "telegram",
]

[list]
showHero = true
showDate = true
heroStyle = "background"            # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = false        # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = false # only used when heroStyle equals background
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"    # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showTableOfContents = false
cardView = false

[term]
showHero = false
heroStyle = "basic"         # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showTableOfContents = false
groupByYear = true
cardView = true
cardViewScreenWidth = false

[firebase]
# apiKey = "XXXXXX"
# authDomain = "XXXXXX"
# projectId = "XXXXXX"
# storageBucket = "XXXXXX"
# messagingSenderId = "XXXXXX"
# appId = "XXXXXX"
# measurementId = "XXXXXX"

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[umamiAnalytics]
# websiteid = "ABC12345"
# domain = "llama.yoursite.com"
# dataDomains = "yoursite.com,yoursite2.com"
# scriptName = ""
# enableTrackEvent = true

[selineAnalytics]
# token = "XXXXXX"
# enableTrackEvent = true

[buymeacoffee]
# identifier = ""
# globalWidget = true
# globalWidgetMessage = "Hello"
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "Right"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
# fediverse = ""

[rssnext]
# feedId = ""
# userId = ""
